name: seetle
description: "seetle."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  url_strategy: ^0.3.0
  dio: ^5.7.0
  go_router: ^14.6.3
  fluttertoast: ^8.2.10
  rxdart: ^0.28.0
  loading_indicator: ^3.1.1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^5.0.0
  carousel_indicator: ^1.0.6
  shared_preferences: ^2.1.0
  grouped_list: ^6.0.0
  provider: ^6.1.2
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  toastification: ^2.3.0
  file_picker: ^8.1.7
  dotted_border: ^2.1.0
  country_picker: ^2.0.27
  intl: ^0.20.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.1
  permission_handler: ^11.4.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  dashed_line: ^0.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
  - assets/
  - assets/images/icons/
  - assets/images/background/

  fonts:
  - family: Onset
    fonts:
      - asset: assets/fonts/Onest-Regular.ttf
        weight: 700
  - family: Onset-Normal
    fonts:
      - asset: assets/fonts/Onest-Primary.ttf
        weight: 500
  - family: Onset-Regular
    fonts:
      - asset: assets/fonts/Onest-Primary.ttf
        weight: 200